
version: '3.9'
services:
  db:
    image: postgres
    container_name: only-to-install-postgress
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      -
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"